name: Build & Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up env.properties
        run: |
          echo "ADMOB_ID=${{ secrets.ADMOB_ID }}" >> env.properties
          echo "AD_BANNER_UNIT_ID=${{ secrets.AD_BANNER_UNIT_ID }}" >> env.properties
          echo "AD_INTERSTITIAL_UNIT_ID=${{ secrets.AD_INTERSTITIAL_UNIT_ID }}" >> env.properties
          echo "API_KEY_DEBUG=${{ secrets.API_KEY_DEBUG }}" >> env.properties
          echo "BASE_URL_DEBUG=${{ secrets.BASE_URL_DEBUG }}" >> env.properties
          echo "BASE_URL_RELEASE=${{ secrets.BASE_URL_RELEASE }}" >> env.properties

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > ${{ github.workspace }}/keystore.jks

      - name: Build Release AAB
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Determine Track
        id: track
        run: |
          if [[ "${{ github.ref_name }}" == *"-beta" ]]; then
            echo "track=beta" >> $GITHUB_OUTPUT
          else
            echo "track=production" >> $GITHUB_OUTPUT
          fi

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.dapascript.mever
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: ${{ steps.track.outputs.track }}
          status: completed
          whatsNewDirectory: distribution/whatsnew

